### PR TITLE
Convert the list to a csv table

### PR DESCRIPTION
**Pull request by u1735067**
Make it easier to use :)
Also includes list from https://github.com/restic/others/issues/18, with the added tags.
And some informations about the great duplicati.

### CODE REVIEW

**Comment by u1735067** [comment]
See also: 
- https://wiki.gentoo.org/wiki/Project:Infrastructure/Backups_v3
- https://wiki.archlinux.org/index.php/Synchronization_and_backup_programs

**Comment by fd0** [comment]
Thank you for your contribution! While this is a nice idea, it seems that by default the table isn't shown. Is there any way to show the table by default? I don't like that it's now hidden behind a link, although the table is much nicer.

Can we maybe format a table in Markdown or RST instead?

**Comment by u1735067** [comment]
gh-pages + a script to load & format the csv ?
That's probably related to https://github.com/restic/others/issues/13
But I'm just proposing the csv :)

**Comment by u1735067** [comment]
https://github.com/derekeder/csv-to-html-table
https://derekeder.github.io/csv-to-html-table/ ?

**Comment by fd0** [comment]
I'll close this PR for now, let us know if you like to build something which renders CSV nicely. Thanks!

**Pull request closed without merging**
