### PR TITLE
Convert existing data to filterable HTML table with TableFilter js

### PR DESCRIPTION
**Pull request by kisst**
Just turn on github web pages and boom https://kisst.github.io/others/ has it deployed right now.

### CODE REVIEW

**Comment by kisst** [comment]
Apologies for the mass notification, but as this repo seams a bit lonely... I wanted to check if I should try to get this merged, or just take the repo and work on it outside the frame, as you can see there is a lot of data-point missing,  but before I fill the gaps, just wanted to check if you want to keep this under your domain.
So here comes the noise: @fw42 @fd0 @fawick @zcalusic @scoddy @middelink @MichaelEischer

**Comment by fd0** [comment]
Very nice work! The layout could be improved, but the functionality is great! Since we don't use GitHub pages any more (restic.github.io just redirects to restic.net), I'm not sure about hosting it. Would you like to take over this project?

**Comment by kisst** [comment]
I have to think about it, as from the response time you can guess I'm pretty low on free time myself as well, but I guess I can create a small org for it, and then can handle that a bit more openly then the restic core team.

**Comment by AngelOnFira** [comment]
Hey, I just wanted to chime in on this. With the number of stars on this repo, it's quite clear that there is a need for this type of list, even if only to see why Restic might be the right path. I'd be interested in becoming a maintainer on this repo if there is interest. Although I don't know everything about the topic, I can still clean it up a bit. I maintain several other open source projects, so this won't be too out of the way for me to look over once in a while.

As for the hosting of Github Pages, It might be beneficial to host at a subdomain such as `others.restic.net`, or `restic.net/others` which should be automatically set up with how Github Pages works. For me, I'd like to learn about what's out there, but it would also be beneficial for you to have this attached to your project I think. Anyways, let me know if this sounds like a good path!

Just going to ping @fd0 to make sure this gets to you :100:

**Comment by cfcs** [comment]
@kisst @fd0 @AngelOnFira 
I think the table @kisst made looks great; would it be possible to have a subpage on restic.net which linked to a static/raw file here like @AngelOnFira suggests?

**Pull request closed without merging**
