### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by tomato42**
update the state of rclone and rdiff-backup

### CODE REVIEW

**Comment by fd0** [comment]
Hey, thanks for taking the time to improve the list. I'm not sure if `rclone` qualifies as a "backup program". Does it have specific backup functionality, more than "move the target files away if they already exist"?

**Comment by tomato42** [comment]
That's how I've seen it described, and it targets storage with primary use case of backup (e.g. backblaze).

Use of rsync for backup is rather well established too...

**Comment by fd0** [comment]
I know, I'm trying to establish a rough guideline on which programs to include and which not. Otherwise we'd also need to list `tar` and `cp` (since they are used for backup) and then the list is less valuable :) The ideal list would only list software specialized for backups.

At the moment I'm leaning towards not including `rclone`. Your other change (for `rdiff-backup`) is fine. Shall I cherry-pick it, or do you want to remove the rclone commit from this PR?

**Comment by tomato42** [comment]
well, the point is that the update of the backup does not require re-sending the whole set again, I'd say having rsync included would be useful, tar and cp not so much

but it's your call, if don't want it, please cherry-pick, I won't be able to rework the PR till Monday

**Comment by fd0** [comment]
I'll do that, thanks for your contribution!

**Comment by fd0** [comment]
Fixed in b6f9af78afb7d8dcee89ea82c5f274a16f2b1960

**Pull request closed without merging**
